/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ButtonColor,
  Color,
  Size,
} from './interfaces/interfaces';
import {
  ColumnSize,
  Narrow,
} from './components/column/column';
import {
  Stage,
} from './components/columns/columns';
import {
  ImageSize,
} from './components/image/image';

export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface OktBox {
    'href': string;
    'isLink': boolean;
  }
  interface OktBreadcrumb {
    'alignment': 'centered' | 'right';
    'separator': 'arrow' | 'bullet' | 'dot' | 'succeeds';
    'size': Size;
  }
  interface OktBulma {}
  interface OktButton {
    'active': boolean;
    'color': ButtonColor;
    'disabled': boolean;
    'focused': boolean;
    'fullWidth': boolean;
    'hovered': boolean;
    'href': string;
    'inverted': boolean;
    'light': boolean;
    'loading': boolean;
    'outlined': boolean;
    'rounded': boolean;
    'size': Size;
    'tag': 'a' | 'button' | 'input';
    'type': 'submit' | 'reset' | 'button';
  }
  interface OktButtons {
    'addons': boolean;
    'alignment': 'centered' | 'right';
    'size': Size;
  }
  interface OktCallout {
    'color': Color;
  }
  interface OktCard {}
  interface OktCardContent {}
  interface OktCardFooter {}
  interface OktCardHeader {}
  interface OktCardImage {}
  interface OktCode {}
  interface OktColumn {
    'columns': ColumnSize;
    'desktop': ColumnSize;
    'fullhd': ColumnSize;
    'mobile': ColumnSize;
    'narrow': Narrow;
    'offset': ColumnSize;
    'offsetDesktop': ColumnSize;
    'offsetFullhd': ColumnSize;
    'offsetMobile': ColumnSize;
    'offsetTablet': ColumnSize;
    'offsetTouch': ColumnSize;
    'offsetWidescreen': ColumnSize;
    'tablet': ColumnSize;
    'touch': ColumnSize;
    'widescreen': ColumnSize;
  }
  interface OktColumns {
    'centered': boolean;
    'gap': number;
    'gapDesktop': number;
    'gapFullhd': number;
    'gapMobile': number;
    'gapTablet': number;
    'gapWidescreen': number;
    'gapless': boolean;
    'multiline': boolean;
    'stage': Stage;
    'variable': boolean;
    'vcentered': boolean;
  }
  interface OktContainer {
    'breakpoint': 'widescreen' | 'fullhd';
    'fluid': boolean;
  }
  interface OktContent {
    'size': Size;
  }
  interface OktControl {
    'expanded': boolean;
    'iconLeft': boolean;
    'iconRight': boolean;
  }
  interface OktDemo {}
  interface OktDemoBox {}
  interface OktDemoBreadcrumb {}
  interface OktDemoButton {}
  interface OktDemoCard {}
  interface OktDemoColumn {}
  interface OktDemoContainer {}
  interface OktDemoContent {}
  interface OktDemoDropdown {}
  interface OktDemoIcon {}
  interface OktDemoImage {}
  interface OktDemoMenu {}
  interface OktDemoNotification {}
  interface OktDemoProgress {}
  interface OktDemoTable {}
  interface OktDemoTag {}
  interface OktDropdown {
    'active': boolean;
    'hoverable': boolean;
    'right': boolean;
    'up': boolean;
  }
  interface OktDropdownDivider {}
  interface OktField {
    'addons': boolean;
    'addonsAlignment': 'centered' | 'right';
    'groupAlignment': 'centered' | 'right';
    'grouped': boolean;
    'groupedMultiline': boolean;
    'horizontal': boolean;
  }
  interface OktIcon {
    'color': Color | 'link';
    'size': Size;
  }
  interface OktImage {
    'alt': string;
    'hideImage': boolean;
    'rounded': boolean;
    'size': 16 | 24 | 32 | 48 | 64 | 96 | 128 | ImageSize;
    'src': string;
  }
  interface OktMedia {}
  interface OktMediaContent {}
  interface OktMediaLeft {}
  interface OktMenu {}
  interface OktMenuLabel {}
  interface OktMenuList {}
  interface OktNotification {
    'color': Color | 'link';
  }
  interface OktProgress {
    'color': Color | 'link';
    'max': string;
    'size': Size;
    'value': string;
  }
  interface OktRoot {}
  interface OktTable {
    'bordered': boolean;
    'fullWidth': boolean;
    'hoverable': boolean;
    'narrow': boolean;
    'scrollable': boolean;
    'striped': boolean;
  }
  interface OktTableContainer {}
  interface OktTag {
    'color': Color | 'link';
    'del': boolean;
    'light': boolean;
    'rounded': boolean;
    'size': Size;
  }
  interface OktTags {
    'addons': boolean;
    'size': Size;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLOktBoxElement extends Components.OktBox, HTMLStencilElement {}
  var HTMLOktBoxElement: {
    prototype: HTMLOktBoxElement;
    new (): HTMLOktBoxElement;
  };

  interface HTMLOktBreadcrumbElement extends Components.OktBreadcrumb, HTMLStencilElement {}
  var HTMLOktBreadcrumbElement: {
    prototype: HTMLOktBreadcrumbElement;
    new (): HTMLOktBreadcrumbElement;
  };

  interface HTMLOktBulmaElement extends Components.OktBulma, HTMLStencilElement {}
  var HTMLOktBulmaElement: {
    prototype: HTMLOktBulmaElement;
    new (): HTMLOktBulmaElement;
  };

  interface HTMLOktButtonElement extends Components.OktButton, HTMLStencilElement {}
  var HTMLOktButtonElement: {
    prototype: HTMLOktButtonElement;
    new (): HTMLOktButtonElement;
  };

  interface HTMLOktButtonsElement extends Components.OktButtons, HTMLStencilElement {}
  var HTMLOktButtonsElement: {
    prototype: HTMLOktButtonsElement;
    new (): HTMLOktButtonsElement;
  };

  interface HTMLOktCalloutElement extends Components.OktCallout, HTMLStencilElement {}
  var HTMLOktCalloutElement: {
    prototype: HTMLOktCalloutElement;
    new (): HTMLOktCalloutElement;
  };

  interface HTMLOktCardElement extends Components.OktCard, HTMLStencilElement {}
  var HTMLOktCardElement: {
    prototype: HTMLOktCardElement;
    new (): HTMLOktCardElement;
  };

  interface HTMLOktCardContentElement extends Components.OktCardContent, HTMLStencilElement {}
  var HTMLOktCardContentElement: {
    prototype: HTMLOktCardContentElement;
    new (): HTMLOktCardContentElement;
  };

  interface HTMLOktCardFooterElement extends Components.OktCardFooter, HTMLStencilElement {}
  var HTMLOktCardFooterElement: {
    prototype: HTMLOktCardFooterElement;
    new (): HTMLOktCardFooterElement;
  };

  interface HTMLOktCardHeaderElement extends Components.OktCardHeader, HTMLStencilElement {}
  var HTMLOktCardHeaderElement: {
    prototype: HTMLOktCardHeaderElement;
    new (): HTMLOktCardHeaderElement;
  };

  interface HTMLOktCardImageElement extends Components.OktCardImage, HTMLStencilElement {}
  var HTMLOktCardImageElement: {
    prototype: HTMLOktCardImageElement;
    new (): HTMLOktCardImageElement;
  };

  interface HTMLOktCodeElement extends Components.OktCode, HTMLStencilElement {}
  var HTMLOktCodeElement: {
    prototype: HTMLOktCodeElement;
    new (): HTMLOktCodeElement;
  };

  interface HTMLOktColumnElement extends Components.OktColumn, HTMLStencilElement {}
  var HTMLOktColumnElement: {
    prototype: HTMLOktColumnElement;
    new (): HTMLOktColumnElement;
  };

  interface HTMLOktColumnsElement extends Components.OktColumns, HTMLStencilElement {}
  var HTMLOktColumnsElement: {
    prototype: HTMLOktColumnsElement;
    new (): HTMLOktColumnsElement;
  };

  interface HTMLOktContainerElement extends Components.OktContainer, HTMLStencilElement {}
  var HTMLOktContainerElement: {
    prototype: HTMLOktContainerElement;
    new (): HTMLOktContainerElement;
  };

  interface HTMLOktContentElement extends Components.OktContent, HTMLStencilElement {}
  var HTMLOktContentElement: {
    prototype: HTMLOktContentElement;
    new (): HTMLOktContentElement;
  };

  interface HTMLOktControlElement extends Components.OktControl, HTMLStencilElement {}
  var HTMLOktControlElement: {
    prototype: HTMLOktControlElement;
    new (): HTMLOktControlElement;
  };

  interface HTMLOktDemoElement extends Components.OktDemo, HTMLStencilElement {}
  var HTMLOktDemoElement: {
    prototype: HTMLOktDemoElement;
    new (): HTMLOktDemoElement;
  };

  interface HTMLOktDemoBoxElement extends Components.OktDemoBox, HTMLStencilElement {}
  var HTMLOktDemoBoxElement: {
    prototype: HTMLOktDemoBoxElement;
    new (): HTMLOktDemoBoxElement;
  };

  interface HTMLOktDemoBreadcrumbElement extends Components.OktDemoBreadcrumb, HTMLStencilElement {}
  var HTMLOktDemoBreadcrumbElement: {
    prototype: HTMLOktDemoBreadcrumbElement;
    new (): HTMLOktDemoBreadcrumbElement;
  };

  interface HTMLOktDemoButtonElement extends Components.OktDemoButton, HTMLStencilElement {}
  var HTMLOktDemoButtonElement: {
    prototype: HTMLOktDemoButtonElement;
    new (): HTMLOktDemoButtonElement;
  };

  interface HTMLOktDemoCardElement extends Components.OktDemoCard, HTMLStencilElement {}
  var HTMLOktDemoCardElement: {
    prototype: HTMLOktDemoCardElement;
    new (): HTMLOktDemoCardElement;
  };

  interface HTMLOktDemoColumnElement extends Components.OktDemoColumn, HTMLStencilElement {}
  var HTMLOktDemoColumnElement: {
    prototype: HTMLOktDemoColumnElement;
    new (): HTMLOktDemoColumnElement;
  };

  interface HTMLOktDemoContainerElement extends Components.OktDemoContainer, HTMLStencilElement {}
  var HTMLOktDemoContainerElement: {
    prototype: HTMLOktDemoContainerElement;
    new (): HTMLOktDemoContainerElement;
  };

  interface HTMLOktDemoContentElement extends Components.OktDemoContent, HTMLStencilElement {}
  var HTMLOktDemoContentElement: {
    prototype: HTMLOktDemoContentElement;
    new (): HTMLOktDemoContentElement;
  };

  interface HTMLOktDemoDropdownElement extends Components.OktDemoDropdown, HTMLStencilElement {}
  var HTMLOktDemoDropdownElement: {
    prototype: HTMLOktDemoDropdownElement;
    new (): HTMLOktDemoDropdownElement;
  };

  interface HTMLOktDemoIconElement extends Components.OktDemoIcon, HTMLStencilElement {}
  var HTMLOktDemoIconElement: {
    prototype: HTMLOktDemoIconElement;
    new (): HTMLOktDemoIconElement;
  };

  interface HTMLOktDemoImageElement extends Components.OktDemoImage, HTMLStencilElement {}
  var HTMLOktDemoImageElement: {
    prototype: HTMLOktDemoImageElement;
    new (): HTMLOktDemoImageElement;
  };

  interface HTMLOktDemoMenuElement extends Components.OktDemoMenu, HTMLStencilElement {}
  var HTMLOktDemoMenuElement: {
    prototype: HTMLOktDemoMenuElement;
    new (): HTMLOktDemoMenuElement;
  };

  interface HTMLOktDemoNotificationElement extends Components.OktDemoNotification, HTMLStencilElement {}
  var HTMLOktDemoNotificationElement: {
    prototype: HTMLOktDemoNotificationElement;
    new (): HTMLOktDemoNotificationElement;
  };

  interface HTMLOktDemoProgressElement extends Components.OktDemoProgress, HTMLStencilElement {}
  var HTMLOktDemoProgressElement: {
    prototype: HTMLOktDemoProgressElement;
    new (): HTMLOktDemoProgressElement;
  };

  interface HTMLOktDemoTableElement extends Components.OktDemoTable, HTMLStencilElement {}
  var HTMLOktDemoTableElement: {
    prototype: HTMLOktDemoTableElement;
    new (): HTMLOktDemoTableElement;
  };

  interface HTMLOktDemoTagElement extends Components.OktDemoTag, HTMLStencilElement {}
  var HTMLOktDemoTagElement: {
    prototype: HTMLOktDemoTagElement;
    new (): HTMLOktDemoTagElement;
  };

  interface HTMLOktDropdownElement extends Components.OktDropdown, HTMLStencilElement {}
  var HTMLOktDropdownElement: {
    prototype: HTMLOktDropdownElement;
    new (): HTMLOktDropdownElement;
  };

  interface HTMLOktDropdownDividerElement extends Components.OktDropdownDivider, HTMLStencilElement {}
  var HTMLOktDropdownDividerElement: {
    prototype: HTMLOktDropdownDividerElement;
    new (): HTMLOktDropdownDividerElement;
  };

  interface HTMLOktFieldElement extends Components.OktField, HTMLStencilElement {}
  var HTMLOktFieldElement: {
    prototype: HTMLOktFieldElement;
    new (): HTMLOktFieldElement;
  };

  interface HTMLOktIconElement extends Components.OktIcon, HTMLStencilElement {}
  var HTMLOktIconElement: {
    prototype: HTMLOktIconElement;
    new (): HTMLOktIconElement;
  };

  interface HTMLOktImageElement extends Components.OktImage, HTMLStencilElement {}
  var HTMLOktImageElement: {
    prototype: HTMLOktImageElement;
    new (): HTMLOktImageElement;
  };

  interface HTMLOktMediaElement extends Components.OktMedia, HTMLStencilElement {}
  var HTMLOktMediaElement: {
    prototype: HTMLOktMediaElement;
    new (): HTMLOktMediaElement;
  };

  interface HTMLOktMediaContentElement extends Components.OktMediaContent, HTMLStencilElement {}
  var HTMLOktMediaContentElement: {
    prototype: HTMLOktMediaContentElement;
    new (): HTMLOktMediaContentElement;
  };

  interface HTMLOktMediaLeftElement extends Components.OktMediaLeft, HTMLStencilElement {}
  var HTMLOktMediaLeftElement: {
    prototype: HTMLOktMediaLeftElement;
    new (): HTMLOktMediaLeftElement;
  };

  interface HTMLOktMenuElement extends Components.OktMenu, HTMLStencilElement {}
  var HTMLOktMenuElement: {
    prototype: HTMLOktMenuElement;
    new (): HTMLOktMenuElement;
  };

  interface HTMLOktMenuLabelElement extends Components.OktMenuLabel, HTMLStencilElement {}
  var HTMLOktMenuLabelElement: {
    prototype: HTMLOktMenuLabelElement;
    new (): HTMLOktMenuLabelElement;
  };

  interface HTMLOktMenuListElement extends Components.OktMenuList, HTMLStencilElement {}
  var HTMLOktMenuListElement: {
    prototype: HTMLOktMenuListElement;
    new (): HTMLOktMenuListElement;
  };

  interface HTMLOktNotificationElement extends Components.OktNotification, HTMLStencilElement {}
  var HTMLOktNotificationElement: {
    prototype: HTMLOktNotificationElement;
    new (): HTMLOktNotificationElement;
  };

  interface HTMLOktProgressElement extends Components.OktProgress, HTMLStencilElement {}
  var HTMLOktProgressElement: {
    prototype: HTMLOktProgressElement;
    new (): HTMLOktProgressElement;
  };

  interface HTMLOktRootElement extends Components.OktRoot, HTMLStencilElement {}
  var HTMLOktRootElement: {
    prototype: HTMLOktRootElement;
    new (): HTMLOktRootElement;
  };

  interface HTMLOktTableElement extends Components.OktTable, HTMLStencilElement {}
  var HTMLOktTableElement: {
    prototype: HTMLOktTableElement;
    new (): HTMLOktTableElement;
  };

  interface HTMLOktTableContainerElement extends Components.OktTableContainer, HTMLStencilElement {}
  var HTMLOktTableContainerElement: {
    prototype: HTMLOktTableContainerElement;
    new (): HTMLOktTableContainerElement;
  };

  interface HTMLOktTagElement extends Components.OktTag, HTMLStencilElement {}
  var HTMLOktTagElement: {
    prototype: HTMLOktTagElement;
    new (): HTMLOktTagElement;
  };

  interface HTMLOktTagsElement extends Components.OktTags, HTMLStencilElement {}
  var HTMLOktTagsElement: {
    prototype: HTMLOktTagsElement;
    new (): HTMLOktTagsElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'okt-box': HTMLOktBoxElement;
    'okt-breadcrumb': HTMLOktBreadcrumbElement;
    'okt-bulma': HTMLOktBulmaElement;
    'okt-button': HTMLOktButtonElement;
    'okt-buttons': HTMLOktButtonsElement;
    'okt-callout': HTMLOktCalloutElement;
    'okt-card': HTMLOktCardElement;
    'okt-card-content': HTMLOktCardContentElement;
    'okt-card-footer': HTMLOktCardFooterElement;
    'okt-card-header': HTMLOktCardHeaderElement;
    'okt-card-image': HTMLOktCardImageElement;
    'okt-code': HTMLOktCodeElement;
    'okt-column': HTMLOktColumnElement;
    'okt-columns': HTMLOktColumnsElement;
    'okt-container': HTMLOktContainerElement;
    'okt-content': HTMLOktContentElement;
    'okt-control': HTMLOktControlElement;
    'okt-demo': HTMLOktDemoElement;
    'okt-demo-box': HTMLOktDemoBoxElement;
    'okt-demo-breadcrumb': HTMLOktDemoBreadcrumbElement;
    'okt-demo-button': HTMLOktDemoButtonElement;
    'okt-demo-card': HTMLOktDemoCardElement;
    'okt-demo-column': HTMLOktDemoColumnElement;
    'okt-demo-container': HTMLOktDemoContainerElement;
    'okt-demo-content': HTMLOktDemoContentElement;
    'okt-demo-dropdown': HTMLOktDemoDropdownElement;
    'okt-demo-icon': HTMLOktDemoIconElement;
    'okt-demo-image': HTMLOktDemoImageElement;
    'okt-demo-menu': HTMLOktDemoMenuElement;
    'okt-demo-notification': HTMLOktDemoNotificationElement;
    'okt-demo-progress': HTMLOktDemoProgressElement;
    'okt-demo-table': HTMLOktDemoTableElement;
    'okt-demo-tag': HTMLOktDemoTagElement;
    'okt-dropdown': HTMLOktDropdownElement;
    'okt-dropdown-divider': HTMLOktDropdownDividerElement;
    'okt-field': HTMLOktFieldElement;
    'okt-icon': HTMLOktIconElement;
    'okt-image': HTMLOktImageElement;
    'okt-media': HTMLOktMediaElement;
    'okt-media-content': HTMLOktMediaContentElement;
    'okt-media-left': HTMLOktMediaLeftElement;
    'okt-menu': HTMLOktMenuElement;
    'okt-menu-label': HTMLOktMenuLabelElement;
    'okt-menu-list': HTMLOktMenuListElement;
    'okt-notification': HTMLOktNotificationElement;
    'okt-progress': HTMLOktProgressElement;
    'okt-root': HTMLOktRootElement;
    'okt-table': HTMLOktTableElement;
    'okt-table-container': HTMLOktTableContainerElement;
    'okt-tag': HTMLOktTagElement;
    'okt-tags': HTMLOktTagsElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface OktBox {
    'href'?: string;
    'isLink'?: boolean;
  }
  interface OktBreadcrumb {
    'alignment'?: 'centered' | 'right';
    'separator'?: 'arrow' | 'bullet' | 'dot' | 'succeeds';
    'size'?: Size;
  }
  interface OktBulma {}
  interface OktButton {
    'active'?: boolean;
    'color'?: ButtonColor;
    'disabled'?: boolean;
    'focused'?: boolean;
    'fullWidth'?: boolean;
    'hovered'?: boolean;
    'href'?: string;
    'inverted'?: boolean;
    'light'?: boolean;
    'loading'?: boolean;
    'outlined'?: boolean;
    'rounded'?: boolean;
    'size'?: Size;
    'tag'?: 'a' | 'button' | 'input';
    'type'?: 'submit' | 'reset' | 'button';
  }
  interface OktButtons {
    'addons'?: boolean;
    'alignment'?: 'centered' | 'right';
    'size'?: Size;
  }
  interface OktCallout {
    'color'?: Color;
  }
  interface OktCard {}
  interface OktCardContent {}
  interface OktCardFooter {}
  interface OktCardHeader {}
  interface OktCardImage {}
  interface OktCode {}
  interface OktColumn {
    'columns'?: ColumnSize;
    'desktop'?: ColumnSize;
    'fullhd'?: ColumnSize;
    'mobile'?: ColumnSize;
    'narrow'?: Narrow;
    'offset'?: ColumnSize;
    'offsetDesktop'?: ColumnSize;
    'offsetFullhd'?: ColumnSize;
    'offsetMobile'?: ColumnSize;
    'offsetTablet'?: ColumnSize;
    'offsetTouch'?: ColumnSize;
    'offsetWidescreen'?: ColumnSize;
    'tablet'?: ColumnSize;
    'touch'?: ColumnSize;
    'widescreen'?: ColumnSize;
  }
  interface OktColumns {
    'centered'?: boolean;
    'gap'?: number;
    'gapDesktop'?: number;
    'gapFullhd'?: number;
    'gapMobile'?: number;
    'gapTablet'?: number;
    'gapWidescreen'?: number;
    'gapless'?: boolean;
    'multiline'?: boolean;
    'stage'?: Stage;
    'variable'?: boolean;
    'vcentered'?: boolean;
  }
  interface OktContainer {
    'breakpoint'?: 'widescreen' | 'fullhd';
    'fluid'?: boolean;
  }
  interface OktContent {
    'size'?: Size;
  }
  interface OktControl {
    'expanded'?: boolean;
    'iconLeft'?: boolean;
    'iconRight'?: boolean;
  }
  interface OktDemo {}
  interface OktDemoBox {}
  interface OktDemoBreadcrumb {}
  interface OktDemoButton {}
  interface OktDemoCard {}
  interface OktDemoColumn {}
  interface OktDemoContainer {}
  interface OktDemoContent {}
  interface OktDemoDropdown {}
  interface OktDemoIcon {}
  interface OktDemoImage {}
  interface OktDemoMenu {}
  interface OktDemoNotification {}
  interface OktDemoProgress {}
  interface OktDemoTable {}
  interface OktDemoTag {}
  interface OktDropdown {
    'active'?: boolean;
    'hoverable'?: boolean;
    'right'?: boolean;
    'up'?: boolean;
  }
  interface OktDropdownDivider {}
  interface OktField {
    'addons'?: boolean;
    'addonsAlignment'?: 'centered' | 'right';
    'groupAlignment'?: 'centered' | 'right';
    'grouped'?: boolean;
    'groupedMultiline'?: boolean;
    'horizontal'?: boolean;
  }
  interface OktIcon {
    'color'?: Color | 'link';
    'size'?: Size;
  }
  interface OktImage {
    'alt'?: string;
    'hideImage'?: boolean;
    'rounded'?: boolean;
    'size'?: 16 | 24 | 32 | 48 | 64 | 96 | 128 | ImageSize;
    'src'?: string;
  }
  interface OktMedia {}
  interface OktMediaContent {}
  interface OktMediaLeft {}
  interface OktMenu {}
  interface OktMenuLabel {}
  interface OktMenuList {}
  interface OktNotification {
    'color'?: Color | 'link';
  }
  interface OktProgress {
    'color'?: Color | 'link';
    'max'?: string;
    'size'?: Size;
    'value'?: string;
  }
  interface OktRoot {}
  interface OktTable {
    'bordered'?: boolean;
    'fullWidth'?: boolean;
    'hoverable'?: boolean;
    'narrow'?: boolean;
    'scrollable'?: boolean;
    'striped'?: boolean;
  }
  interface OktTableContainer {}
  interface OktTag {
    'color'?: Color | 'link';
    'del'?: boolean;
    'light'?: boolean;
    'rounded'?: boolean;
    'size'?: Size;
  }
  interface OktTags {
    'addons'?: boolean;
    'size'?: Size;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'okt-box': OktBox;
    'okt-breadcrumb': OktBreadcrumb;
    'okt-bulma': OktBulma;
    'okt-button': OktButton;
    'okt-buttons': OktButtons;
    'okt-callout': OktCallout;
    'okt-card': OktCard;
    'okt-card-content': OktCardContent;
    'okt-card-footer': OktCardFooter;
    'okt-card-header': OktCardHeader;
    'okt-card-image': OktCardImage;
    'okt-code': OktCode;
    'okt-column': OktColumn;
    'okt-columns': OktColumns;
    'okt-container': OktContainer;
    'okt-content': OktContent;
    'okt-control': OktControl;
    'okt-demo': OktDemo;
    'okt-demo-box': OktDemoBox;
    'okt-demo-breadcrumb': OktDemoBreadcrumb;
    'okt-demo-button': OktDemoButton;
    'okt-demo-card': OktDemoCard;
    'okt-demo-column': OktDemoColumn;
    'okt-demo-container': OktDemoContainer;
    'okt-demo-content': OktDemoContent;
    'okt-demo-dropdown': OktDemoDropdown;
    'okt-demo-icon': OktDemoIcon;
    'okt-demo-image': OktDemoImage;
    'okt-demo-menu': OktDemoMenu;
    'okt-demo-notification': OktDemoNotification;
    'okt-demo-progress': OktDemoProgress;
    'okt-demo-table': OktDemoTable;
    'okt-demo-tag': OktDemoTag;
    'okt-dropdown': OktDropdown;
    'okt-dropdown-divider': OktDropdownDivider;
    'okt-field': OktField;
    'okt-icon': OktIcon;
    'okt-image': OktImage;
    'okt-media': OktMedia;
    'okt-media-content': OktMediaContent;
    'okt-media-left': OktMediaLeft;
    'okt-menu': OktMenu;
    'okt-menu-label': OktMenuLabel;
    'okt-menu-list': OktMenuList;
    'okt-notification': OktNotification;
    'okt-progress': OktProgress;
    'okt-root': OktRoot;
    'okt-table': OktTable;
    'okt-table-container': OktTableContainer;
    'okt-tag': OktTag;
    'okt-tags': OktTags;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'okt-box': LocalJSX.OktBox & JSXBase.HTMLAttributes<HTMLOktBoxElement>;
      'okt-breadcrumb': LocalJSX.OktBreadcrumb & JSXBase.HTMLAttributes<HTMLOktBreadcrumbElement>;
      'okt-bulma': LocalJSX.OktBulma & JSXBase.HTMLAttributes<HTMLOktBulmaElement>;
      'okt-button': LocalJSX.OktButton & JSXBase.HTMLAttributes<HTMLOktButtonElement>;
      'okt-buttons': LocalJSX.OktButtons & JSXBase.HTMLAttributes<HTMLOktButtonsElement>;
      'okt-callout': LocalJSX.OktCallout & JSXBase.HTMLAttributes<HTMLOktCalloutElement>;
      'okt-card': LocalJSX.OktCard & JSXBase.HTMLAttributes<HTMLOktCardElement>;
      'okt-card-content': LocalJSX.OktCardContent & JSXBase.HTMLAttributes<HTMLOktCardContentElement>;
      'okt-card-footer': LocalJSX.OktCardFooter & JSXBase.HTMLAttributes<HTMLOktCardFooterElement>;
      'okt-card-header': LocalJSX.OktCardHeader & JSXBase.HTMLAttributes<HTMLOktCardHeaderElement>;
      'okt-card-image': LocalJSX.OktCardImage & JSXBase.HTMLAttributes<HTMLOktCardImageElement>;
      'okt-code': LocalJSX.OktCode & JSXBase.HTMLAttributes<HTMLOktCodeElement>;
      'okt-column': LocalJSX.OktColumn & JSXBase.HTMLAttributes<HTMLOktColumnElement>;
      'okt-columns': LocalJSX.OktColumns & JSXBase.HTMLAttributes<HTMLOktColumnsElement>;
      'okt-container': LocalJSX.OktContainer & JSXBase.HTMLAttributes<HTMLOktContainerElement>;
      'okt-content': LocalJSX.OktContent & JSXBase.HTMLAttributes<HTMLOktContentElement>;
      'okt-control': LocalJSX.OktControl & JSXBase.HTMLAttributes<HTMLOktControlElement>;
      'okt-demo': LocalJSX.OktDemo & JSXBase.HTMLAttributes<HTMLOktDemoElement>;
      'okt-demo-box': LocalJSX.OktDemoBox & JSXBase.HTMLAttributes<HTMLOktDemoBoxElement>;
      'okt-demo-breadcrumb': LocalJSX.OktDemoBreadcrumb & JSXBase.HTMLAttributes<HTMLOktDemoBreadcrumbElement>;
      'okt-demo-button': LocalJSX.OktDemoButton & JSXBase.HTMLAttributes<HTMLOktDemoButtonElement>;
      'okt-demo-card': LocalJSX.OktDemoCard & JSXBase.HTMLAttributes<HTMLOktDemoCardElement>;
      'okt-demo-column': LocalJSX.OktDemoColumn & JSXBase.HTMLAttributes<HTMLOktDemoColumnElement>;
      'okt-demo-container': LocalJSX.OktDemoContainer & JSXBase.HTMLAttributes<HTMLOktDemoContainerElement>;
      'okt-demo-content': LocalJSX.OktDemoContent & JSXBase.HTMLAttributes<HTMLOktDemoContentElement>;
      'okt-demo-dropdown': LocalJSX.OktDemoDropdown & JSXBase.HTMLAttributes<HTMLOktDemoDropdownElement>;
      'okt-demo-icon': LocalJSX.OktDemoIcon & JSXBase.HTMLAttributes<HTMLOktDemoIconElement>;
      'okt-demo-image': LocalJSX.OktDemoImage & JSXBase.HTMLAttributes<HTMLOktDemoImageElement>;
      'okt-demo-menu': LocalJSX.OktDemoMenu & JSXBase.HTMLAttributes<HTMLOktDemoMenuElement>;
      'okt-demo-notification': LocalJSX.OktDemoNotification & JSXBase.HTMLAttributes<HTMLOktDemoNotificationElement>;
      'okt-demo-progress': LocalJSX.OktDemoProgress & JSXBase.HTMLAttributes<HTMLOktDemoProgressElement>;
      'okt-demo-table': LocalJSX.OktDemoTable & JSXBase.HTMLAttributes<HTMLOktDemoTableElement>;
      'okt-demo-tag': LocalJSX.OktDemoTag & JSXBase.HTMLAttributes<HTMLOktDemoTagElement>;
      'okt-dropdown': LocalJSX.OktDropdown & JSXBase.HTMLAttributes<HTMLOktDropdownElement>;
      'okt-dropdown-divider': LocalJSX.OktDropdownDivider & JSXBase.HTMLAttributes<HTMLOktDropdownDividerElement>;
      'okt-field': LocalJSX.OktField & JSXBase.HTMLAttributes<HTMLOktFieldElement>;
      'okt-icon': LocalJSX.OktIcon & JSXBase.HTMLAttributes<HTMLOktIconElement>;
      'okt-image': LocalJSX.OktImage & JSXBase.HTMLAttributes<HTMLOktImageElement>;
      'okt-media': LocalJSX.OktMedia & JSXBase.HTMLAttributes<HTMLOktMediaElement>;
      'okt-media-content': LocalJSX.OktMediaContent & JSXBase.HTMLAttributes<HTMLOktMediaContentElement>;
      'okt-media-left': LocalJSX.OktMediaLeft & JSXBase.HTMLAttributes<HTMLOktMediaLeftElement>;
      'okt-menu': LocalJSX.OktMenu & JSXBase.HTMLAttributes<HTMLOktMenuElement>;
      'okt-menu-label': LocalJSX.OktMenuLabel & JSXBase.HTMLAttributes<HTMLOktMenuLabelElement>;
      'okt-menu-list': LocalJSX.OktMenuList & JSXBase.HTMLAttributes<HTMLOktMenuListElement>;
      'okt-notification': LocalJSX.OktNotification & JSXBase.HTMLAttributes<HTMLOktNotificationElement>;
      'okt-progress': LocalJSX.OktProgress & JSXBase.HTMLAttributes<HTMLOktProgressElement>;
      'okt-root': LocalJSX.OktRoot & JSXBase.HTMLAttributes<HTMLOktRootElement>;
      'okt-table': LocalJSX.OktTable & JSXBase.HTMLAttributes<HTMLOktTableElement>;
      'okt-table-container': LocalJSX.OktTableContainer & JSXBase.HTMLAttributes<HTMLOktTableContainerElement>;
      'okt-tag': LocalJSX.OktTag & JSXBase.HTMLAttributes<HTMLOktTagElement>;
      'okt-tags': LocalJSX.OktTags & JSXBase.HTMLAttributes<HTMLOktTagsElement>;
    }
  }
}


