/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ButtonColor,
  Size,
} from './interfaces/interfaces';

export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface OktBulma {}
  interface OktButton {
    'active': boolean;
    'color': ButtonColor;
    'disabled': boolean;
    'fullWidth': boolean;
    'href': string;
    'inverted': boolean;
    'light': boolean;
    'loading': boolean;
    'outlined': boolean;
    'rounded': boolean;
    'size': Size;
    'tag': 'a' | 'button' | 'input';
    'type': 'submit' | 'reset' | 'button';
  }
  interface OktDemo {}
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLOktBulmaElement extends Components.OktBulma, HTMLStencilElement {}
  var HTMLOktBulmaElement: {
    prototype: HTMLOktBulmaElement;
    new (): HTMLOktBulmaElement;
  };

  interface HTMLOktButtonElement extends Components.OktButton, HTMLStencilElement {}
  var HTMLOktButtonElement: {
    prototype: HTMLOktButtonElement;
    new (): HTMLOktButtonElement;
  };

  interface HTMLOktDemoElement extends Components.OktDemo, HTMLStencilElement {}
  var HTMLOktDemoElement: {
    prototype: HTMLOktDemoElement;
    new (): HTMLOktDemoElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'okt-bulma': HTMLOktBulmaElement;
    'okt-button': HTMLOktButtonElement;
    'okt-demo': HTMLOktDemoElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface OktBulma {}
  interface OktButton {
    'active'?: boolean;
    'color'?: ButtonColor;
    'disabled'?: boolean;
    'fullWidth'?: boolean;
    'href'?: string;
    'inverted'?: boolean;
    'light'?: boolean;
    'loading'?: boolean;
    'outlined'?: boolean;
    'rounded'?: boolean;
    'size'?: Size;
    'tag'?: 'a' | 'button' | 'input';
    'type'?: 'submit' | 'reset' | 'button';
  }
  interface OktDemo {}

  interface IntrinsicElements {
    'my-component': MyComponent;
    'okt-bulma': OktBulma;
    'okt-button': OktButton;
    'okt-demo': OktDemo;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'okt-bulma': LocalJSX.OktBulma & JSXBase.HTMLAttributes<HTMLOktBulmaElement>;
      'okt-button': LocalJSX.OktButton & JSXBase.HTMLAttributes<HTMLOktButtonElement>;
      'okt-demo': LocalJSX.OktDemo & JSXBase.HTMLAttributes<HTMLOktDemoElement>;
    }
  }
}


